namespace Shelyak.Usis.Enums;

public enum DeviceProperty
{
    DEVICE_NAME,
    SOFTWARE_VERSION,
    PROTOCOL_VERSION,
    TEMPERATURE,
    HUMIDITY,
    
    GRATING_ID,
    GRATING_ANGLE,
    GRATING_ANGLE_MAX,
    GRAITNG_ANGLE_MIN,
    GRAITNG_ANGLE_PREC,
    GRATING_WAVELENGTH,
    GRATING_DENSITY,
    
    SLIT_ID,
    SLIT_WIDTH,
    SLIT_ANGLE,
    
    FOCUS_POSITION,
    
    LIGHT_SOURCE
}