//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shelyak.Uvex.Web.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shelyak.Uvex.Web.Locales.LocalizationResources", typeof(LocalizationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibrate.
        /// </summary>
        public static string Button_Calibrate {
            get {
                return ResourceManager.GetString("Button_Calibrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to.
        /// </summary>
        public static string Button_Go_to {
            get {
                return ResourceManager.GetString("Button_Go to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halt.
        /// </summary>
        public static string Button_Halt {
            get {
                return ResourceManager.GetString("Button_Halt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown.
        /// </summary>
        public static string Button_Shutdown {
            get {
                return ResourceManager.GetString("Button_Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UVEX.
        /// </summary>
        public static string Configuration_ComPort_CardTitle_UVEX {
            get {
                return ResourceManager.GetString("Configuration_ComPort_CardTitle_UVEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating the COM port configuration.
        /// </summary>
        public static string Configuration_ComPort_Command_Error {
            get {
                return ResourceManager.GetString("Configuration_ComPort_Command_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COM port configuration updated successfully.
        /// </summary>
        public static string Configuration_ComPort_Command_Success {
            get {
                return ResourceManager.GetString("Configuration_ComPort_Command_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COM port.
        /// </summary>
        public static string Configuration_ComPort_Label_COM_Port {
            get {
                return ResourceManager.GetString("Configuration_ComPort_Label_COM Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string Configuration_Shutdown_CardTitle_Server {
            get {
                return ResourceManager.GetString("Configuration_Shutdown_CardTitle_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to shutdown the server?.
        /// </summary>
        public static string Configuration_Shutdown_Confirmation_Info {
            get {
                return ResourceManager.GetString("Configuration_Shutdown_Confirmation_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server shutdown.
        /// </summary>
        public static string Configuration_Shutdown_Confirmation_Title {
            get {
                return ResourceManager.GetString("Configuration_Shutdown_Confirmation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown the server.
        /// </summary>
        public static string Configuration_Shutdown_server {
            get {
                return ResourceManager.GetString("Configuration_Shutdown server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swagger - Web API.
        /// </summary>
        public static string Configuration_Swagger_CardTitle {
            get {
                return ResourceManager.GetString("Configuration_Swagger_CardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating the Swagger configuration.
        /// </summary>
        public static string Configuration_Swagger_Command_Error {
            get {
                return ResourceManager.GetString("Configuration_Swagger_Command_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swagger configuration updated successfully.
        /// </summary>
        public static string Configuration_Swagger_Command_Success {
            get {
                return ResourceManager.GetString("Configuration_Swagger_Command_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swagger is a web interface that lets you interact directly with the device using the API. A server restart is required after a configuration change..
        /// </summary>
        public static string Configuration_Swagger_Info {
            get {
                return ResourceManager.GetString("Configuration_Swagger_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Configuration_Swagger_Label_Enabled {
            get {
                return ResourceManager.GetString("Configuration_Swagger_Label_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Configuration_Title {
            get {
                return ResourceManager.GetString("Configuration_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swagger.
        /// </summary>
        public static string NavMenu_API {
            get {
                return ResourceManager.GetString("NavMenu_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string NavMenu_Configuration {
            get {
                return ResourceManager.GetString("NavMenu_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls.
        /// </summary>
        public static string NavMenu_Controls {
            get {
                return ResourceManager.GetString("NavMenu_Controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration.
        /// </summary>
        public static string UvexControl_Calibration_CardTitle {
            get {
                return ResourceManager.GetString("UvexControl_Calibration_CardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration.
        /// </summary>
        public static string UvexControl_Calibration_Switch_Calibration {
            get {
                return ResourceManager.GetString("UvexControl_Calibration_Switch_Calibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string UvexControl_Calibration_Switch_Dark {
            get {
                return ResourceManager.GetString("UvexControl_Calibration_Switch_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat.
        /// </summary>
        public static string UvexControl_Calibration_Switch_Flat {
            get {
                return ResourceManager.GetString("UvexControl_Calibration_Switch_Flat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sky.
        /// </summary>
        public static string UvexControl_Calibration_Switch_Sky {
            get {
                return ResourceManager.GetString("UvexControl_Calibration_Switch_Sky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus.
        /// </summary>
        public static string UvexControl_Focus_CardTitle {
            get {
                return ResourceManager.GetString("UvexControl_Focus_CardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current position.
        /// </summary>
        public static string UvexControl_Focus_Label_Current_position {
            get {
                return ResourceManager.GetString("UvexControl_Focus_Label_Current position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step size.
        /// </summary>
        public static string UvexControl_Focus_Label_Step_size {
            get {
                return ResourceManager.GetString("UvexControl_Focus_Label_Step size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target position.
        /// </summary>
        public static string UvexControl_Focus_Label_Target_position {
            get {
                return ResourceManager.GetString("UvexControl_Focus_Label_Target position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grating angle.
        /// </summary>
        public static string UvexControl_GratingAngle_CardTitle {
            get {
                return ResourceManager.GetString("UvexControl_GratingAngle_CardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current angle.
        /// </summary>
        public static string UvexControl_GratingAngle_Label_Current_angle {
            get {
                return ResourceManager.GetString("UvexControl_GratingAngle_Label_Current angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step size.
        /// </summary>
        public static string UvexControl_GratingAngle_Label_Step_size {
            get {
                return ResourceManager.GetString("UvexControl_GratingAngle_Label_Step size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target angle.
        /// </summary>
        public static string UvexControl_GratingAngle_Label_Target_angle {
            get {
                return ResourceManager.GetString("UvexControl_GratingAngle_Label_Target angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wavelength.
        /// </summary>
        public static string UvexControl_GratingWavelength_CardTitle {
            get {
                return ResourceManager.GetString("UvexControl_GratingWavelength_CardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current wavelength.
        /// </summary>
        public static string UvexControl_GratingWavelength_Label_Current_wavelength {
            get {
                return ResourceManager.GetString("UvexControl_GratingWavelength_Label_Current wavelength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step size.
        /// </summary>
        public static string UvexControl_GratingWavelength_Label_Step_size {
            get {
                return ResourceManager.GetString("UvexControl_GratingWavelength_Label_Step size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target wavelength.
        /// </summary>
        public static string UvexControl_GratingWavelength_Label_Target_wavelength {
            get {
                return ResourceManager.GetString("UvexControl_GratingWavelength_Label_Target wavelength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations.
        /// </summary>
        public static string UvexControl_Informations_CardTitle {
            get {
                return ResourceManager.GetString("UvexControl_Informations_CardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COM port.
        /// </summary>
        public static string UvexControl_Informations_Label_COM_port {
            get {
                return ResourceManager.GetString("UvexControl_Informations_Label_COM port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware.
        /// </summary>
        public static string UvexControl_Informations_Label_Firmware {
            get {
                return ResourceManager.GetString("UvexControl_Informations_Label_Firmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol version.
        /// </summary>
        public static string UvexControl_Informations_Label_Protocol_version {
            get {
                return ResourceManager.GetString("UvexControl_Informations_Label_Protocol version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectrograph.
        /// </summary>
        public static string UvexControl_Informations_Label_Spectrograph_name {
            get {
                return ResourceManager.GetString("UvexControl_Informations_Label_Spectrograph name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensors.
        /// </summary>
        public static string UvexControl_Sensors_CardTitle {
            get {
                return ResourceManager.GetString("UvexControl_Sensors_CardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string UvexControl_Sensors_Label_Temperature {
            get {
                return ResourceManager.GetString("UvexControl_Sensors_Label_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UVEX Control.
        /// </summary>
        public static string UvexControl_Title {
            get {
                return ResourceManager.GetString("UvexControl_Title", resourceCulture);
            }
        }
    }
}
