name: 'Build'
on:
  workflow_call:
    inputs:
      gitversion-config:
        description: 'Path to GitVersion configuration file'
        required: true
        type: string
      build_installer:
        description: 'Push the generated installer in artifact'
        default: false
        required: false
        type: boolean
        
    outputs:
      MajorMinorPatch:
        value: ${{ jobs.build.outputs.MajorMinorPatch }}
      SemVer:
        value: ${{ jobs.build.outputs.SemVer }}
        
env:
  dotnet_version: 'net8.0'
  installer_artifact_name: 'installers'
  artifacts_retention_days: 5

jobs:
  build:
    name: 'Build (Sub-Workflow)'
    runs-on: windows-latest
    outputs:
      MajorMinorPatch: ${{ steps.gitversion.outputs.MajorMinorPatch }}
      SemVer: ${{ steps.gitversion.outputs.SemVer }}
      
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0

      - name: 'Setup MSBuild'
        uses: microsoft/setup-msbuild@v2

      - name: 'Setup GitVersion'
        uses: gittools/actions/gitversion/setup@v1.2.0
        with:
          versionSpec: '5.x'

      - name: 'GitVersion updateassemblyinfo'
        uses: gittools/actions/gitversion/execute@v1.2.0
        with:
          useConfigFile: true
          configFilePath: ${{ inputs.gitversion-config }}
          additionalArguments: '/updateassemblyinfo'

      - name: 'GitVersion updateprojectfiles'
        id:   gitversion
        uses: gittools/actions/gitversion/execute@v1.2.0
        with:
          useConfigFile: true
          configFilePath: ${{ inputs.gitversion-config }}
          additionalArguments: '/updateprojectfiles'

      - name: 'Restore Shelyak.Uvex.Ascom'
        run: nuget restore Shelyak.Uvex.Ascom.sln

      - name: 'Build Shelyak.Uvex.Ascom'
        run: msbuild Shelyak.Uvex.Ascom.sln /p:Configuration=Release /p:RestorePackages=false

      - name: 'Restore Shelyak.Uvex.Web'
        run: dotnet restore Shelyak.Uvex.sln

      - name: 'Publish Shelyak.Uvex.Web'
        run: dotnet publish Shelyak.Uvex.Web.sln --configuration Release --arch x64 --self-contained true --framework ${{ env.dotnet_version }}
        
      - name: 'Test Shelyak.Uvex.Web'
        run: dotnet test Shelyak.Uvex.Web.sln --configuration Release --no-restore --verbosity normal --collect:"XPlat Code Coverage"

      - name: 'Report Generator'
        uses: danielpalme/ReportGenerator-GitHub-Action@5.1.13
        with:
          reports: './**/TestResults/**/coverage.cobertura.xml'
          targetdir: 'coveragereport'
          reporttypes: 'HtmlSummary'

      - name: 'Upload coverage report artifact'
        uses: actions/upload-artifact@v4.3.4
        with:
          name: CoverageReport
          path: coveragereport
          retention-days: ${{ inputs.artifacts_retention_days }}

      - name: 'Build Inno Setup Packages'
        if: ${{ inputs.build_installer == true }}
        run: | 
          ISCC /Dversion=${{ steps.gitversion.outputs.MajorMinorPatch }} /DVersionInfoVersion=${{ steps.gitversion.outputs.MajorMinorPatch }} ./Shelyak.Uvex.Ascom/bin/Release/InnoSetup/Setup.iss
          ISCC /Dversion=${{ steps.gitversion.outputs.MajorMinorPatch }} /DVersionInfoVersion=${{ steps.gitversion.outputs.MajorMinorPatch }} ./Shelyak.Uvex.Web/bin/Release/${{ env.dotnet_version }}/win-x64/publish/InnoSetup/Setup.iss
          ISCC /Dversion=${{ steps.gitversion.outputs.MajorMinorPatch }} /DVersionInfoVersion=${{ steps.gitversion.outputs.MajorMinorPatch }} ./InnoSetup/Setup.iss
          mkdir ./installers
          cp ./Shelyak.Uvex.Ascom/bin/Release/InnoSetup/*.exe ./installers/
          cp ./Shelyak.Uvex.Web/bin/Release/${{ env.dotnet_version }}/win-x64/publish/InnoSetup/*.exe ./installers/
          cp ./InnoSetup/*.exe ./installers/
      - name: 'Upload source artifact'
        if: ${{ inputs.build_installer == true }}
        uses: actions/upload-artifact@v4.3.4
        with:
          name: ${{ env.installer_artifact_name }}
          path: ./installers/*.exe
          retention-days: ${{ env.artifacts_retention_days }}
