name: 'Tag & Release (Sub-Workflow)'
on:
  workflow_call:
    inputs:
      git_tag:
        description: 'Git tag to create'
        required: true
        type: string
      changelog_builder_configuration:
        description: 'Relative path to the configuration.json file for the mikepenz/release-changelog-builder-action'
        required: true
        type: string
    
env:
  installer_artifact_name: 'installers'

jobs:
  release:
    name: 'Create Tag and Release'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
        
      - name: 'Download source artifact'
        uses: actions/download-artifact@v4.1.8
        with:
          name: ${{ env.installer_artifact_name }}
          path: ${{ inputs.installer_artifact_name }}
          
      - name: 'Create Tag'
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          tag_prefix: ''
          custom_tag: ${{ inputs.git_tag }}
          github_token: ${{ secrets.GITHUB_TOKEN }}  
    
      - name: 'Build Changelog'
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v4.2.2
        with:
          failOnError: true
          configuration: "${{ inputs.changelog_builder_configuration }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Create Release'
        uses: ncipollo/release-action@v1.12.0
        with:
          artifactErrorsFailBuild: true
          draft: false
          body: "${{steps.build_changelog.outputs.changelog}}"
          tag: "${{ inputs.git_tag }}"
          artifacts: "${{ env.installer_artifact_name }}/*"
          token: ${{ secrets.GITHUB_TOKEN }}
